#!/bin/bash
#
# This hook script verifies what is about to be committed.
# Called by "git commit" with no arguments.
# The hook exits with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

RED="\e[1;31m"
RESET="\e[0m"

ROOT=$(git rev-parse --show-toplevel)
if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
allownonascii=$(git config --bool hooks.allownonascii)
if [ "$allownonascii" != "true" ] &&
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    echo -e "${RED}Error: Attempt to add a non-ASCII file name.${RESET}"
    echo "This can cause problems if you want to work with people on other platforms."
    echo "To be portable it is advisable to rename the file."
    echo
    echo "If you know what you are doing you can disable this check using:"
    echo "    git -c hooks.allow_non_ascii=true commit"
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
allowtrailing=$(git config --bool hooks.allowtrailingwhitespace)
if [ "$allowtrailing" != "true" ]; then
    git diff-index --check --cached $against --
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Trailing whitespace found in one or more files.${RESET}"
        echo
        echo "If you know what you are doing you can disable this check using:"
        echo "    git -c hooks.allowtrailingwhitespace=true commit"
        exit 1
    fi
fi
